//! SSH tunnel end-to-end: drive the real binary through a real `ssh` tunnel to
//! a PostgreSQL that is reachable from the bastion's docker network by its
//! container name.
//!
//! Stand (needs Docker/colima; fails, not skips, without one — like the
//! Postgres tests): a throwaway user-defined network holds a `postgres:16-alpine`
//! (reachable on the network by its container name) and a
//! `linuxserver/openssh-server` bastion (its 2222 published to the host). A
//! per-test ed25519 keypair (generated by shelling out to `ssh-keygen`, no new
//! crate) authorizes into the bastion.
//!
//! Injecting the test key / host-key policy: OpenSSH resolves `~/.ssh/config`
//! from the *passwd* home (getpwuid), ignoring `$HOME`, so a temp HOME cannot
//! redirect the client config. Instead we put a tiny `ssh` shim first on the
//! PATH nyet runs with; the shim execs the real ssh with `-F <test config>`
//! (identity file, `StrictHostKeyChecking no`, throwaway known_hosts). nyet is
//! otherwise exercised for real: it builds the ssh command, opens the `-L`
//! forward to `<pg>:5432`, and the Postgres engine connects to the local end.
//!
//! Note: testcontainers still publishes Postgres's 5432 to a random host port;
//! "only reachable from the bastion" is about the tunnel path we exercise (the
//! forward targets the container's network name, not the host port), not
//! host-level isolation.

use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::process::{Command, Output};
use std::time::{Duration, Instant, SystemTime};
use testcontainers_modules::postgres::Postgres as PgImage;
use testcontainers_modules::testcontainers::core::{
    CmdWaitFor, ExecCommand, IntoContainerPort, WaitFor,
};
use testcontainers_modules::testcontainers::runners::AsyncRunner;
use testcontainers_modules::testcontainers::{GenericImage, ImageExt};

const PW: &str = "s3cr3t_pw_xyz";
const PW_ENV: &str = "NYET_SSH_TEST_PW";
/// `latest` pinned to a digest (see the comment at the call site). `docker pull
/// linuxserver/openssh-server` + `docker inspect --format '{{index .RepoDigests 0}}'`
/// to refresh; `latest@sha256:...` is a valid ref and docker resolves by digest.
const OPENSSH_TAG: &str =
    "latest@sha256:9c5e178975fcc3917853f5e37cbf135ad7deb11de504ab0f460cc81a2e1eb539";

fn multi_thread_rt() -> tokio::runtime::Runtime {
    tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .unwrap()
}

/// Run the binary with a clean environment plus HOME, the password env var, and
/// a PATH whose first entry (`bin_dir`) holds the ssh shim.
fn run(home: &Path, bin_dir: &Path, cfg: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_nyet"))
        .env_clear()
        .env("HOME", home)
        .env(PW_ENV, PW)
        .env("PATH", format!("{}:/usr/bin:/bin", bin_dir.display()))
        .current_dir(home)
        .args(args)
        .arg("--config")
        .arg(cfg)
        .output()
        .unwrap()
}

fn stdout(out: &Output) -> String {
    String::from_utf8_lossy(&out.stdout).into_owned()
}
fn stderr(out: &Output) -> String {
    String::from_utf8_lossy(&out.stderr).into_owned()
}

/// Absolute path of the real system ssh (the shim is not on the test's own PATH).
fn real_ssh() -> String {
    for dir in std::env::var("PATH").unwrap_or_default().split(':') {
        let p = Path::new(dir).join("ssh");
        if p.is_file() {
            return p.to_string_lossy().into_owned();
        }
    }
    "/usr/bin/ssh".to_string()
}

/// Generate a throwaway ed25519 keypair via ssh-keygen; return the public key.
fn gen_keypair(dir: &Path) -> String {
    let key = dir.join("id_ed25519");
    let status = Command::new("ssh-keygen")
        .args(["-t", "ed25519", "-N", "", "-q", "-f"])
        .arg(&key)
        .status()
        .expect("ssh-keygen must be installed");
    assert!(status.success(), "ssh-keygen failed");
    std::fs::read_to_string(dir.join("id_ed25519.pub")).unwrap()
}

/// Write the test ssh config + an `ssh` shim that injects it via `-F`, and
/// return the bin dir to prepend to PATH.
fn setup_ssh_shim(dir: &Path) -> std::path::PathBuf {
    let cfg = dir.join("ssh_config");
    std::fs::write(
        &cfg,
        format!(
            "Host *\n\
             \tUser nyet\n\
             \tIdentityFile {id}\n\
             \tIdentitiesOnly yes\n\
             \tStrictHostKeyChecking no\n\
             \tUserKnownHostsFile /dev/null\n\
             \tLogLevel ERROR\n",
            id = dir.join("id_ed25519").display(),
        ),
    )
    .unwrap();

    let bin = dir.join("bin");
    std::fs::create_dir_all(&bin).unwrap();
    let shim = bin.join("ssh");
    // Dump this ssh invocation's environment (before exec, so it is exactly the
    // env nyet handed to the ssh child) so the test can prove the DB password
    // was stripped. `exec` is kept so nyet's Child handle is ssh itself (kill
    // works, no orphan).
    std::fs::write(
        &shim,
        format!(
            "#!/bin/sh\nenv > {dump}\nexec {ssh} -F {cfg} \"$@\"\n",
            dump = dir.join("ssh_env_dump").display(),
            ssh = real_ssh(),
            cfg = cfg.display(),
        ),
    )
    .unwrap();
    std::fs::set_permissions(&shim, std::fs::Permissions::from_mode(0o755)).unwrap();
    bin
}

fn write_config(dir: &Path, ssh_port: u16, pg_name: &str) -> std::path::PathBuf {
    let path = dir.join("config.toml");
    // The url host/port are placeholders — the tunnel overrides them to the
    // local forward; the user (postgres) and dbname (postgres) are kept.
    std::fs::write(
        &path,
        format!(
            "[connections.pg]\nengine = \"postgres\"\n\
             url = \"postgres://postgres@db.placeholder:5432/postgres\"\n\
             password_env = \"{PW_ENV}\"\nallowed_dirs = [\"{}\"]\n\
             [connections.pg.ssh]\n\
             host = \"nyet@127.0.0.1:{ssh_port}\"\n\
             remote = \"{pg_name}:5432\"\n\
             control_persist = \"5s\"\n",
            dir.display(),
        ),
    )
    .unwrap();
    path
}

/// Poll until a *fresh* (no ControlMaster) `-L` forward through the bastion
/// actually reaches Postgres. This gates on the real capability — sshd up, key
/// authorized, AND `AllowTcpForwarding` reloaded after the HUP — so nyet's first
/// attempt (which creates a persistent master) is made only once forwarding is
/// live, avoiding a poisoned master reused with the old policy.
fn wait_for_forwarding(bin_dir: &Path, ssh_port: u16, pg_name: &str) {
    let deadline = Instant::now() + Duration::from_secs(45);
    loop {
        if forward_reaches_pg(bin_dir, ssh_port, pg_name) {
            return;
        }
        assert!(
            Instant::now() < deadline,
            "bastion forwarding did not become ready"
        );
        std::thread::sleep(Duration::from_millis(500));
    }
}

/// Open a throwaway `-L` forward (no master) and check Postgres answers through
/// it; returns false if auth, forwarding policy, or the DB are not ready yet.
fn forward_reaches_pg(bin_dir: &Path, ssh_port: u16, pg_name: &str) -> bool {
    let Ok(listener) = TcpListener::bind("127.0.0.1:0") else {
        return false;
    };
    let probe = listener.local_addr().unwrap().port();
    drop(listener);
    let fwd = format!("127.0.0.1:{probe}:{pg_name}:5432");
    let ok = Command::new("ssh")
        .env_clear()
        .env("PATH", format!("{}:/usr/bin:/bin", bin_dir.display()))
        .args([
            "-f",
            "-N",
            "-o",
            "BatchMode=yes",
            "-o",
            "ExitOnForwardFailure=yes",
            "-o",
            "ControlMaster=no",
            "-o",
            "ConnectTimeout=5",
            "-L",
            &fwd,
            "-p",
            &ssh_port.to_string(),
            "127.0.0.1",
        ])
        .status()
        .map(|s| s.success())
        .unwrap_or(false);
    if !ok {
        return false;
    }
    std::thread::sleep(Duration::from_millis(200));
    let reached = postgres_answers(probe);
    // Reap the throwaway forward (best effort; it also dies with the bastion).
    let _ = Command::new("pkill").args(["-f", &fwd]).status();
    reached
}

/// Send a Postgres SSLRequest and see if the server answers a byte. A forward
/// that the bastion refuses resets the connection instead (no byte).
fn postgres_answers(port: u16) -> bool {
    let Ok(mut s) = TcpStream::connect(("127.0.0.1", port)) else {
        return false;
    };
    let _ = s.set_read_timeout(Some(Duration::from_secs(3)));
    // SSLRequest: int32 length=8, int32 code=80877103 (0x04d2162f).
    if s.write_all(&[0, 0, 0, 8, 0x04, 0xd2, 0x16, 0x2f]).is_err() {
        return false;
    }
    let mut b = [0u8; 1];
    matches!(s.read(&mut b), Ok(1))
}

fn unique_suffix() -> String {
    let nanos = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    format!("{}-{}", std::process::id(), nanos)
}

/// Full happy path: SELECT through the tunnel returns rows (exit 0).
#[test]
fn ssh_tunnel_query_end_to_end() {
    multi_thread_rt().block_on(async {
        let suffix = unique_suffix();
        let net = format!("nyet-ssh-net-{suffix}");
        let pg_name = format!("nyet-ssh-pg-{suffix}");

        // Postgres: reachable on the network under `pg_name`; seeded.
        let pg = PgImage::default()
            .with_password(PW)
            .with_tag("16-alpine")
            .with_network(&net)
            .with_container_name(&pg_name)
            .start()
            .await
            .expect("start postgres:16-alpine (is docker/colima running?)");
        let pg_host_port = pg.get_host_port_ipv4(5432).await.unwrap();
        {
            use sqlx::{ConnectOptions, Connection, Executor};
            let opts: sqlx::postgres::PgConnectOptions =
                format!("postgres://postgres@127.0.0.1:{pg_host_port}/postgres")
                    .parse()
                    .unwrap();
            let mut w = opts.password(PW).connect().await.unwrap();
            w.execute("CREATE TABLE users (id int primary key, email text)")
                .await
                .unwrap();
            w.execute("INSERT INTO users VALUES (1, 'a@b.c'), (2, 'd@e.f')")
                .await
                .unwrap();
            w.close().await.unwrap();
        }

        let home = tempfile::tempdir().unwrap();
        let pubkey = gen_keypair(home.path());
        let bin_dir = setup_ssh_shim(home.path());

        // Bastion: openssh with our public key, 2222 published to the host.
        // Pinned by digest (not floating `latest`) so a future image release
        // cannot silently change the init banner / config path / process name
        // this stand depends on and turn CI red on an unrelated day.
        let bastion = GenericImage::new("linuxserver/openssh-server", OPENSSH_TAG)
            .with_wait_for(WaitFor::message_on_stdout("[ls.io-init] done."))
            .with_exposed_port(2222.tcp())
            .with_network(&net)
            .with_env_var("PUBLIC_KEY", pubkey.trim())
            .with_env_var("USER_NAME", "nyet")
            .with_env_var("PASSWORD_ACCESS", "false")
            .with_env_var("PUID", "1000")
            .with_env_var("PGID", "1000")
            .start()
            .await
            .expect("start linuxserver/openssh-server");
        let ssh_port = bastion.get_host_port_ipv4(2222).await.unwrap();

        // linuxserver/openssh-server ships `AllowTcpForwarding no` in its live
        // config (/config/sshd/sshd_config) — a bastion that forbids the very
        // forward we need. Flip it and SIGHUP sshd to reload. This is stand
        // setup, not something nyet does.
        bastion
            .exec(
                ExecCommand::new([
                    "sh",
                    "-c",
                    // pkill (not `kill -HUP $(pgrep ...)`): a drifted image that
                    // renames the process yields no PID, and `kill` with no arg
                    // would hard-fail the exec; pkill just exits non-zero, which
                    // the tunnel retry below then absorbs.
                    "sed -i 's/^AllowTcpForwarding.*/AllowTcpForwarding yes/' \
                     /config/sshd/sshd_config; pkill -HUP -f sshd.pam",
                ])
                .with_cmd_ready_condition(CmdWaitFor::exit()),
            )
            .await
            .expect("enable TCP forwarding on the bastion");

        wait_for_forwarding(&bin_dir, ssh_port, &pg_name);

        // Retry the whole tunnel pass: sshd re-reading its config after the HUP
        // is not instant, so the first attempt can hit `AllowTcpForwarding no`
        // still in effect and fail with exit 6 (ExitOnForwardFailure). Back off
        // until forwarding is live.
        let cfg = write_config(home.path(), ssh_port, &pg_name);
        let deadline = Instant::now() + Duration::from_secs(30);
        let out = loop {
            let out = run(
                home.path(),
                &bin_dir,
                &cfg,
                &["query", "pg", "SELECT id, email FROM users ORDER BY id"],
            );
            if out.status.code() == Some(0) || Instant::now() >= deadline {
                break out;
            }
            std::thread::sleep(Duration::from_millis(500));
        };
        assert_eq!(
            out.status.code(),
            Some(0),
            "stdout={}\nstderr={}",
            stdout(&out),
            stderr(&out)
        );
        let v: serde_json::Value = serde_json::from_str(stdout(&out).trim()).unwrap();
        assert_eq!(v["ok"], true);
        assert_eq!(
            v["rows"],
            serde_json::json!([
                {"id": 1, "email": "a@b.c"},
                {"id": 2, "email": "d@e.f"},
            ])
        );
        assert_eq!(v["meta"]["connection"], "pg");
        // The distinctive password must never leak (threat model).
        assert!(!stdout(&out).contains(PW) && !stderr(&out).contains(PW));
        // ...and the ssh child's environment (dumped by the shim) must not carry
        // the DB password var — nyet sanitizes the env it hands to ssh.
        let ssh_env = std::fs::read_to_string(home.path().join("ssh_env_dump")).unwrap();
        assert!(
            !ssh_env.contains(PW) && !ssh_env.contains(PW_ENV),
            "ssh child inherited the DB password: {ssh_env}"
        );

        // No forward accumulation: each `nyet query` tears its forward down on
        // exit (guard Drop kill+wait). Assert no ssh process is left holding a
        // forward to the db. Poll (not an instant assert): nyet reaps its own
        // child synchronously, but the `wait_for_forwarding` probes were pkilled
        // (async) and the OS teardown of a killed process on a loaded runner is
        // not instantaneous — wait for it, then assert. A real leak never
        // reaches 0 and still fails.
        let count_forwards = || {
            let out = Command::new("pgrep")
                .args(["-f", &format!("{pg_name}:5432")])
                .output()
                .unwrap();
            String::from_utf8_lossy(&out.stdout).lines().count()
        };
        let assert_no_forwards = |ctx: &str| {
            let deadline = Instant::now() + Duration::from_secs(5);
            while count_forwards() != 0 {
                assert!(
                    Instant::now() < deadline,
                    "{ctx}: an ssh forward is still present after 5s (leak)"
                );
                std::thread::sleep(Duration::from_millis(200));
            }
        };
        assert_no_forwards("before the repeat runs");
        for _ in 0..3 {
            let out = run(home.path(), &bin_dir, &cfg, &["query", "pg", "SELECT 1"]);
            assert_eq!(out.status.code(), Some(0), "{}", stderr(&out));
            assert_no_forwards("after a query");
        }

        // Async Drop must run inside the runtime.
        bastion.rm().await.unwrap();
        pg.rm().await.unwrap();
    });
}

/// Tunnel failure (unreachable bastion port) -> CONNECTION_FAILED, exit 6.
/// No containers needed: ssh fails to connect before any auth.
#[test]
fn ssh_tunnel_failure_is_exit_6() {
    let home = tempfile::tempdir().unwrap();
    // A closed local port: bind :0, read it, drop the listener.
    let closed = std::net::TcpListener::bind("127.0.0.1:0")
        .unwrap()
        .local_addr()
        .unwrap()
        .port();
    let bin_dir = home.path().to_path_buf(); // no shim: nyet finds system ssh on PATH
    let path = home.path().join("config.toml");
    std::fs::write(
        &path,
        format!(
            "[connections.pg]\nengine = \"postgres\"\n\
             url = \"postgres://postgres@db.placeholder:5432/postgres\"\n\
             allowed_dirs = [\"{}\"]\n\
             [connections.pg.ssh]\n\
             host = \"127.0.0.1:{closed}\"\n\
             remote = \"127.0.0.1:5432\"\n",
            home.path().display(),
        ),
    )
    .unwrap();
    let out = run(
        home.path(),
        &bin_dir,
        &path,
        &["query", "pg", "SELECT 1", "--timeout", "10"],
    );
    assert_eq!(out.status.code(), Some(6), "{}", stdout(&out));
    let v: serde_json::Value = serde_json::from_str(stdout(&out).trim()).unwrap();
    assert_eq!(v["error"]["code"], "CONNECTION_FAILED");
    // The hint must be actionable (Д10).
    assert!(!v["error"]["hint"].as_str().unwrap().is_empty());
}
