[package]
name = "nyetdb-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = "1"

[dependencies.nyetdb]
path = ".."

[[bin]]
name = "sql_validate"
path = "fuzz_targets/sql_validate.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mongo_check"
path = "fuzz_targets/mongo_check.rs"
test = false
doc = false
bench = false

[[bin]]
name = "mongo_pii"
path = "fuzz_targets/mongo_pii.rs"
test = false
doc = false
bench = false
